### ISSUE TITLE
fix(validator): requiredChecked for checkboxes not working client-side

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#141]
As the title says, `requiredChecked` is not working on the client during `onBlur` event. It is working on server-side rendered pages, but if you use the TAB key to fire an `onBlur` event on the browser, the validation error is cleared.

Can be recreated if you have the following configuration:

```typescript
const form = new FormGroup([
{
	name: 'happy',
	label: 'Happy',
	type: 'checkbox',
	labelPosition: 'right',
	validators: [Validators.requiredChecked]
}])
```

**Comment by Icyscools** [comment]
I have investigated this issue. It's seemed the checkboxes always have value as `on` whether checked or not. It was the default value for the checkbox form. Also, the value of checkboxes is used as a value given to the data submitted with the checkbox's name. (See also in [MDN's doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox))

I think the solution for this issue is to add a condition in the validation function for checkboxes and get a `checked` attribute instead of a `value` attribute.

**Comment by ayoayco** [comment]
Thanks for looking into this! Yes, with this issue, the validation function `requiredChecked` should find the `checked` attribute of the HTML input element. We can focus on just this one validation function, for now, to keep this issue small.
