### ISSUE TITLE
feat(validator): for client-side validation, use unique ID as selector of the form

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#211]
Right now the `<script>` in Validator.astro which defines how event listeners are attached in the browser is using the element `<form>` as selector.

Use the unique ID prefixed with `arl` to select the correct form. :)

**Comment by alexsam29** [comment]
I would also like to work on this, I feel like it's somewhat related to #201.

**Comment by ayoayco** [comment]
I don't mind having the two issues in the same PR @alexsam29 :)

**Comment by alexsam29** [comment]
>1. By default, it will still query by element `form` then filter the ones with ID prefixed "arl" so we know we are working with forms generated by our library

Is this not already implemented by #224? Because we are already selecting by the custom attribute `data-validation-on`, so we already know that we are working with elements generated by our library.

>  2. If the developer wants to use Validator only for a specific form, they can optionally use the Validator component like so: `<Validator validate={['Form name 1', 'Form name 2']} />`

Hmmm still a little confused on this suggestion.  So we pass the form name as a prop, but I'm not sure how I'd be able to use the that to enable validation on the selected form. I can't seem to use any props within `<script>` so I've tried other ways with no success. I feel like I'm missing something.

**Comment by ayoayco** [comment]
I think #2 is not important now with our new approach. It was a way to explicitly say, in a scenario with two or more forms, which ones the developer wants to be client-side validated. I'm closing this issue now and let's just think of that scenario when needed in the future
